workspace:
  base: /test
  path: oe_theme

services:
  web:
    image: fpfis/httpd-php-ci:7.1
    environment:
      - DOCUMENT_ROOT=/test/oe_theme

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer clear-cache

