language: php
dist: precise

php:
  - 7

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin

install:
  - composer self-update
  - composer install

before_script:
  # Start PhantomJS server.
  - phantomjs --webdriver=4444 > /dev/null &
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path=`which true`" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Create database.
  - mysql -e 'create database drupal'
  # Exclude build directory from Drupal and Drush.
  # @todo: Include this in custom scaffolding.
  - echo '$settings["file_scan_ignore_directories"][] = "build";' >> build/sites/default/default.settings.php
  # Install Drupal 8 target site.
  - cd build
  - drush si standard -y --db-url=mysql://travis:@127.0.0.1/drupal --exclude=build
  - drush en oe_core oe_theme oe_theme_test -y --exclude=build
  - drush config-set system.theme default oe_theme -y --exclude=build
  - drush cr --exclude=build
  # Run Drush web server.
  - drush --exclude=build --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s
  - chmod -R ug+w sites

script:
  - cd $TRAVIS_BUILD_DIR
  - grumphp run
  - behat

notifications:
  email: false
