oe_theme.settings:
  type: theme_settings
  label: 'OpenEuropa Theme settings'
  mapping:
    component_library:
      type: string
      label: 'ECL component library, either EC or EU'
    branding:
      type: string
      label: 'Site branding, either core, standardised or harmonised'
