image.effect.retina_image_scale:
  type: image.effect.image_scale
  label: 'Retina Image scale'
  mapping:
    multiplier:
      type: integer
      label: 'Multiplier'

field.formatter.settings.address_custom:
  type: mapping
  label: 'Address custom formatter settings'
  mapping:
    delimiter:
      type: string
      label: 'Delimiter for address items.'
